version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    volumes:
      - pg-data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=test
      - SECRET_KEY_BASE=abcd
      - RAILS_LOG_TO_STDOUT=true
      - DATABASE_URL=postgres://docker:docker@db/subject_manager_demo_app_develop
    entrypoint: bash -c "bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rspec"
volumes:
  pg-data:
