# File empty we are using DATABASE_URL (To adjust test and dev take a look at .env and .env.test files in project dir)
default: &default
  pool: 5
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
